package Test2020;

import java.util.HashMap;
import java.util.Map;

public class DuplicateWords {

	public static void main(String[] args) {
		String str = "Leidos will never ask you to provide payment-related information at any part of the employment application process, "
				+ "nor will Leidos ever advance money as part of the hiring process. "
				+ "And Leidos will communicate with you only through emails that are generated by Leidos.com automated system."
				+ "If you receive an email purporting to be from Leidos that asks for payment-related information or any other personal information, "
				+ "please report the email to Chris Scalia, Leidos’ Senior Vice President of Talent Acquisition";
		String[] strArr = str.split("[ ,.']+");

		System.out.println(strArr.length);
		duplicateWords(str);
		
		String num = "1,2,3,4,1,2,3,5,6.2,3,1, 4 2 3 54 5 1 2 77 44 3 2 11";
		duplicateWords(num);
		duplicateWords("1,2,3,4,1");
	}
	
	public static void duplicateWords(String str) {
		String[] strArr = str.split("[ ,.']+");
		Map<String,Integer> sortMap =  new HashMap<>();
		for (String string : strArr) {
			if(sortMap.containsKey(string)) {
				sortMap.put(string, sortMap.get(string)+1);
			}else {
				sortMap.put(string, 1);
			}
		}
		System.out.println(sortMap);
	}

}
